@echo off
cls
title fcleaner beta 1.1
echo Lansoftprogramming
::set _directory=
set /p _directory=enter name of directory you wish to be cleaned
if not '%_directory%'=='%_directory%' set _directory=%_directory%


set /p _type=enter type (video/audio/image/text/custom): 
if not '%_type%'=='%_type%' set _type=%_type%

set /p _fname= Enter name of folder for items to be placed in: 
if not '%_fname%'=='%_fname%' set _fname=%_fname%

if /i '%_type%'=='video' goto vid
if /i '%_type%'=='audio' goto audio
if /i '%_type%'=='image' goto image
if /i '%_type%'=='text' goto text
if /i '%_type%'=='zip'	goto zip
if /i '%_type%'=='custom' goto custom
pause
:vid
	cd /D %_directory%
	mkdir %_fname%
	move *.avi %_directory%\%_fname%
	move *.mp4 %_directory%\%_fname%
	move *0.264 %_directory%\%_fname%
	move *.3g2 %_directory%\%_fname%
	move *.3gp %_directory%\%_fname%
	move *.3gp2 %_directory%\%_fname%
	move *.3gpp %_directory%\%_fname%
	move *.3gpp2 %_directory%\%_fname%
	move *.3mm %_directory%\%_fname%
	move *.3p2 %_directory%\%_fname%
	move *.60d %_directory%\%_fname%
	move *0.787 %_directory%\%_fname%
	move *0.89 %_directory%\%_fname%
	move *.aaf %_directory%\%_fname%
	move *.aec %_directory%\%_fname%
	move *.aep %_directory%\%_fname%
	move *.aepx %_directory%\%_fname%
	move *.aet %_directory%\%_fname%
	move *.aetx %_directory%\%_fname%
	move *.ajp %_directory%\%_fname%
	move *.ale %_directory%\%_fname%
	move *.am %_directory%\%_fname%
	move *.amc %_directory%\%_fname%
	move *.amv %_directory%\%_fname%
	move *.amx %_directory%\%_fname%
	move *.anim %_directory%\%_fname%
	move *.aqt %_directory%\%_fname%
	move *.arcut %_directory%\%_fname%
	move *.arf %_directory%\%_fname%
	move *.asf %_directory%\%_fname%
	move *.asx %_directory%\%_fname%
	move *.avb %_directory%\%_fname%
	move *.avc %_directory%\%_fname%
	move *.avd %_directory%\%_fname%
	move *.avi %_directory%\%_fname%
	move *.avp %_directory%\%_fname%
	move *.avs %_directory%\%_fname%
	move *.avs %_directory%\%_fname%
	move *.avv %_directory%\%_fname%
	move *.axm %_directory%\%_fname%
	move *.bdm %_directory%\%_fname%
	move *.bdmv %_directory%\%_fname%
	move *.bdt2 %_directory%\%_fname%
	move *.bdt3 %_directory%\%_fname%
	move *.bik %_directory%\%_fname%
	move *.bin %_directory%\%_fname%
	move *.bix %_directory%\%_fname%
	move *.bmk %_directory%\%_fname%
	move *.bnp %_directory%\%_fname%
	move *.box %_directory%\%_fname%
	move *.bs4 %_directory%\%_fname%
	move *.bsf %_directory%\%_fname%
	move *.bvr %_directory%\%_fname%
	move *.byu %_directory%\%_fname%
	move *.camproj %_directory%\%_fname%
	move *.camrec %_directory%\%_fname%
	move *.camv %_directory%\%_fname%
	move *.ced %_directory%\%_fname%
	move *.cel %_directory%\%_fname%
	move *.cine %_directory%\%_fname%
	move *.cip %_directory%\%_fname%
	move *.clpi %_directory%\%_fname%
	move *.cmmp %_directory%\%_fname%
	move *.cmmtpl %_directory%\%_fname%
	move *.cmproj %_directory%\%_fname%
	move *.cmrec %_directory%\%_fname%
	move *.cpi %_directory%\%_fname%
	move *.cst %_directory%\%_fname%
	move *.cvc %_directory%\%_fname%
	move *.d2v %_directory%\%_fname%
	move *.d3v %_directory%\%_fname%
	move *.dat %_directory%\%_fname%
	move *.dav %_directory%\%_fname%
	move *.dce %_directory%\%_fname%
	move *.dck %_directory%\%_fname%
	move *.dcr %_directory%\%_fname%
	move *.dcr %_directory%\%_fname%
	move *.ddat %_directory%\%_fname%
	move *.dif %_directory%\%_fname%
	move *.dir %_directory%\%_fname%
	move *.divx %_directory%\%_fname%
	move *.dlx %_directory%\%_fname%
	move *.dmb %_directory%\%_fname%
	move *.dmsd %_directory%\%_fname%
	move *.dmsd3d %_directory%\%_fname%
	move *.dmsm %_directory%\%_fname%
	move *.dmsm3d %_directory%\%_fname%
	move *.dmss %_directory%\%_fname%
	move *.dmx %_directory%\%_fname%
	move *.dnc %_directory%\%_fname%
	move *.dpa %_directory%\%_fname%
	move *.dpg %_directory%\%_fname%
	move *.dream %_directory%\%_fname%
	move *.dsy %_directory%\%_fname%
	move *.dv %_directory%\%_fname%
	move *.dv-avi %_directory%\%_fname%
	move *.dv4 %_directory%\%_fname%
	move *.dvdmedia %_directory%\%_fname%
	move *.dvr %_directory%\%_fname%
	move *.dvr-ms %_directory%\%_fname%
	move *.dvx %_directory%\%_fname%
	move *.dxr %_directory%\%_fname%
	move *.dzm %_directory%\%_fname%
	move *.dzp %_directory%\%_fname%
	move *.dzt %_directory%\%_fname%
	move *.edl %_directory%\%_fname%
	move *.evo %_directory%\%_fname%
	move *.eye %_directory%\%_fname%
	move *.ezt %_directory%\%_fname%
	move *.f4p %_directory%\%_fname%
	move *.f4v %_directory%\%_fname%
	move *.fbr %_directory%\%_fname%
	move *.fbr %_directory%\%_fname%
	echo 20% done
	move *.fbz %_directory%\%_fname%
	move *.fcp %_directory%\%_fname%
	move *.fcproject %_directory%\%_fname%
	move *.flc %_directory%\%_fname%
	move *.flh %_directory%\%_fname%
	move *.fli %_directory%\%_fname%
	move *.flv %_directory%\%_fname%
	move *.flx %_directory%\%_fname%
	move *.gfp %_directory%\%_fname%
	move *.gl %_directory%\%_fname%
	move *.gom %_directory%\%_fname%
	move *.grasp %_directory%\%_fname%
	move *.gts %_directory%\%_fname%
	move *.gvi %_directory%\%_fname%
	move *.gvp %_directory%\%_fname%
	move *.h264 %_directory%\%_fname%
	move *.hdmov %_directory%\%_fname%
	move *.hkm %_directory%\%_fname%
	move *.ifo %_directory%\%_fname%
	move *.imovieproj %_directory%\%_fname%
	move *.imovieproject %_directory%\%_fname%
	move *.ircp %_directory%\%_fname%
	move *.irf %_directory%\%_fname%
	move *.ism %_directory%\%_fname%
	move *.ismc %_directory%\%_fname%
	move *.ismv %_directory%\%_fname%
	move *.iva %_directory%\%_fname%
	move *.ivf %_directory%\%_fname%
	move *.ivr %_directory%\%_fname%
	move *.ivs %_directory%\%_fname%
	move *.izz %_directory%\%_fname%
	move *.izzy %_directory%\%_fname%
	move *.jss %_directory%\%_fname%
	move *.jts %_directory%\%_fname%
	move *.jtv %_directory%\%_fname%
	move *.k3g %_directory%\%_fname%
	move *.lrec %_directory%\%_fname%
	move *.lsf %_directory%\%_fname%
	move *.lsx %_directory%\%_fname%
	move *.m15 %_directory%\%_fname%
	move *.m1pg %_directory%\%_fname%
	move *.m1v %_directory%\%_fname%
	move *.m21 %_directory%\%_fname%
	move *.m21 %_directory%\%_fname%
	move *.m2a %_directory%\%_fname%
	move *.m2p %_directory%\%_fname%
	move *.m2t %_directory%\%_fname%
	move *.m2ts %_directory%\%_fname%
	move *.m2v %_directory%\%_fname%
	move *.m4e %_directory%\%_fname%
	move *.m4u %_directory%\%_fname%
	move *.m4v %_directory%\%_fname%
	move *.m75 %_directory%\%_fname%
	move *.meta %_directory%\%_fname%
	move *.mgv %_directory%\%_fname%
	move *.mj2 %_directory%\%_fname%
	move *.mjp %_directory%\%_fname%
	move *.mjpg %_directory%\%_fname%
	move *.mk3d %_directory%\%_fname%
	move *.mkv %_directory%\%_fname%
	echo 40%
	move *.mmv %_directory%\%_fname%
	move *.mnv %_directory%\%_fname%
	move *.mob %_directory%\%_fname%
	move *.mod %_directory%\%_fname%
	move *.modd %_directory%\%_fname%
	move *.moff %_directory%\%_fname%
	move *.moi %_directory%\%_fname%
	move *.moov %_directory%\%_fname%
	move *.mov %_directory%\%_fname%
	move *.movie %_directory%\%_fname%
	move *.mp21 %_directory%\%_fname%
	move *.mp21 %_directory%\%_fname%
	move *.mp2v %_directory%\%_fname%
	move *.mp4 %_directory%\%_fname%
	move *.mp4v %_directory%\%_fname%
	move *.mpe %_directory%\%_fname%
	move *.mpeg %_directory%\%_fname%
	move *.mpeg4 %_directory%\%_fname%
	move *.mpf %_directory%\%_fname%
	move *.mpg %_directory%\%_fname%
	move *.mpg2 %_directory%\%_fname%
	move *.mpgindex %_directory%\%_fname%
	move *.mpl %_directory%\%_fname%
	move *.mpl %_directory%\%_fname%
	move *.mpls %_directory%\%_fname%
	move *.mpsub %_directory%\%_fname%
	move *.mpv %_directory%\%_fname%
	move *.mpv2 %_directory%\%_fname%
	move *.mqv %_directory%\%_fname%
	move *.msdvd %_directory%\%_fname%
	move *.mse %_directory%\%_fname%
	move *.msh %_directory%\%_fname%
	move *.mswmm %_directory%\%_fname%
	move *.mts %_directory%\%_fname%
	move *.mtv %_directory%\%_fname%
	move *.mvb %_directory%\%_fname%
	move *.mvc %_directory%\%_fname%
	move *.mvd %_directory%\%_fname%
	move *.mve %_directory%\%_fname%
	move *.mvex %_directory%\%_fname%
	move *.mvp %_directory%\%_fname%
	move *.mvp %_directory%\%_fname%
	move *.mvy %_directory%\%_fname%
	move *.mxf %_directory%\%_fname%
	move *.mys %_directory%\%_fname%
	move *.ncor %_directory%\%_fname%
	move *.nsv %_directory%\%_fname%
	move *.nuv %_directory%\%_fname%
	move *.nvc %_directory%\%_fname%
	move *.ogm %_directory%\%_fname%
	move *.ogv %_directory%\%_fname%
	move *.ogx %_directory%\%_fname%
	move *.osp %_directory%\%_fname%
	echo 60% done
	move *.otrkey %_directory%\%_fname%
	move *.pac %_directory%\%_fname%
	move *.par %_directory%\%_fname%
	move *.pds %_directory%\%_fname%
	move *.pgi %_directory%\%_fname%
	move *.photoshow %_directory%\%_fname%
	move *.piv %_directory%\%_fname%
	move *.pjs %_directory%\%_fname%
	move *.playlist %_directory%\%_fname%
	move *.plproj %_directory%\%_fname%
	move *.pmf %_directory%\%_fname%
	move *.pmv %_directory%\%_fname%
	move *.pns %_directory%\%_fname%
	move *.ppj %_directory%\%_fname%
	move *.prel %_directory%\%_fname%
	move *.pro %_directory%\%_fname%
	move *.prproj %_directory%\%_fname%
	move *.prtl %_directory%\%_fname%
	move *.psb %_directory%\%_fname%
	move *.psh %_directory%\%_fname%
	move *.pssd %_directory%\%_fname%
	move *.pva %_directory%\%_fname%
	move *.pvr %_directory%\%_fname%
	move *.pxv %_directory%\%_fname%
	move *.qt %_directory%\%_fname%
	move *.qtch %_directory%\%_fname%
	move *.qtindex %_directory%\%_fname%
	move *.qtl %_directory%\%_fname%
	move *.qtm %_directory%\%_fname%
	move *.qtz %_directory%\%_fname%
	move *.r3d %_directory%\%_fname%
	move *.rcd /D %_directory%\%_fname%
	move *.rcproject %_directory%\%_fname%
	move *.rdb %_directory%\%_fname%
	move *.rec %_directory%\%_fname%
	move *.rm %_directory%\%_fname%
	move *.rmd %_directory%\%_fname%
	move *.rmd %_directory%\%_fname%
	move *.rmp %_directory%\%_fname%
	move *.rms %_directory%\%_fname%
	move *.rmv %_directory%\%_fname%
	move *.rmvb %_directory%\%_fname%
	move *.roq %_directory%\%_fname%
	move *.rp %_directory%\%_fname%
	move *.rsx %_directory%\%_fname%
	move *.rts %_directory%\%_fname%
	move *.rts %_directory%\%_fname%
	move *.rum %_directory%\%_fname%
	move *.rv %_directory%\%_fname%
	move *.rvl %_directory%\%_fname%
	move *.sbk %_directory%\%_fname%
	move *.sbt %_directory%\%_fname%
	move *.scc %_directory%\%_fname%
	move *.scm %_directory%\%_fname%
	move *.scm %_directory%\%_fname%
	move *.scn %_directory%\%_fname%
	move *.screenflow %_directory%\%_fname%
	move *.sec %_directory%\%_fname%
	move *.sedprj %_directory%\%_fname%
	move *.seq %_directory%\%_fname%
	move *.sfd %_directory%\%_fname%
	move *.sfvidcap %_directory%\%_fname%
	move *.siv %_directory%\%_fname%
	move *.smi %_directory%\%_fname%
	move *.smi %_directory%\%_fname%
	move *.smil %_directory%\%_fname%
	move *.smk %_directory%\%_fname%
	move *.sml %_directory%\%_fname%
	move *.smv %_directory%\%_fname%
	move *.spl %_directory%\%_fname%
	move *.sqz %_directory%\%_fname%
	move *.srt %_directory%\%_fname%
	move *.ssf %_directory%\%_fname%
	move *.ssm %_directory%\%_fname%
	move *.stl %_directory%\%_fname%
	move *.str %_directory%\%_fname%
	move *.stx %_directory%\%_fname%
	move *.svi %_directory%\%_fname%
	move *.swf %_directory%\%_fname%
	move *.swi %_directory%\%_fname%
	move *.swt %_directory%\%_fname%
	move *.tda3mt %_directory%\%_fname%
	move *.tdx %_directory%\%_fname%
	move *.thp %_directory%\%_fname%
	move *.tivo %_directory%\%_fname%
	move *.tix %_directory%\%_fname%
	move *.tod %_directory%\%_fname%
	move *.tp %_directory%\%_fname%
	move *.tp0 %_directory%\%_fname%
	move *.tpd %_directory%\%_fname%
	move *.tpr %_directory%\%_fname%
	move *.trp %_directory%\%_fname%
	move *.ts %_directory%\%_fname%
	echo 80% done
	move *.tsp %_directory%\%_fname%
	move *.ttxt %_directory%\%_fname%
	move *.tvs %_directory%\%_fname%
	move *.usf %_directory%\%_fname%
	move *.usm %_directory%\%_fname%
	move *.vc1 %_directory%\%_fname%
	move *.vcpf %_directory%\%_fname%
	move *.vcr %_directory%\%_fname%
	move *.vcv %_directory%\%_fname%
	move *.vdo %_directory%\%_fname%
	move *.vdr %_directory%\%_fname%
	move *.vdx %_directory%\%_fname%
	move *.veg %_directory%\%_fname%
	move *.vem %_directory%\%_fname%
	move *.vep %_directory%\%_fname%
	move *.vf %_directory%\%_fname%
	move *.vft %_directory%\%_fname%
	move *.vfw %_directory%\%_fname%
	move *.vfz %_directory%\%_fname%
	move *.vgz %_directory%\%_fname%
	move *.vid %_directory%\%_fname%
	move *.video %_directory%\%_fname%
	move *.viewlet %_directory%\%_fname%
	move *.viv %_directory%\%_fname%
	move *.vivo %_directory%\%_fname%
	move *.vlab %_directory%\%_fname%
	move *.vob %_directory%\%_fname%
	move *.vp3 %_directory%\%_fname%
	move *.vp6 %_directory%\%_fname%
	move *.vp7 %_directory%\%_fname%
	move *.vpj %_directory%\%_fname%
	move *.vro %_directory%\%_fname%
	move *.vs4 %_directory%\%_fname%
	move *.vse %_directory%\%_fname%
	move *.vsp %_directory%\%_fname%
	move *.w32 %_directory%\%_fname%
	move *.wcp %_directory%\%_fname%
	move *.webm %_directory%\%_fname%
	move *.wlmp %_directory%\%_fname%
	move *.wm %_directory%\%_fname%
	move *.wmd %_directory%\%_fname%
	move *.wmmp %_directory%\%_fname%
	move *.wmv %_directory%\%_fname%
	move *.wmx %_directory%\%_fname%
	move *.wot %_directory%\%_fname%
	move *.wp3 %_directory%\%_fname%
	move *.wpl %_directory%\%_fname%
	move *.wtv %_directory%\%_fname%
	move *.wvx %_directory%\%_fname%
	move *.xej %_directory%\%_fname%
	move *.xel %_directory%\%_fname%
	move *.xesc %_directory%\%_fname%
	move *.xfl %_directory%\%_fname%
	move *.xlmv %_directory%\%_fname%
	move *.xvid %_directory%\%_fname%
	move *.yuv %_directory%\%_fname%
	move *.zeg %_directory%\%_fname%
	move *.zm1 %_directory%\%_fname%
	move *.zm2 %_directory%\%_fname%
	move *.zm3 %_directory%\%_fname%
	move *.zmv %_directory%\%_fname% 
		goto end
::____________________________________________done_________________
:audio
	cd /D %_directory%
	mkdir %_fname%
	move *.3ga  %_directory%\%_fname%
	move *.4mp  %_directory%\%_fname%
	move *0.669  %_directory%\%_fname%
	move *.6cm  %_directory%\%_fname%
	move *.8cm  %_directory%\%_fname%
	move *.8med  %_directory%\%_fname%
	move *.8svx  %_directory%\%_fname%
	move *.a2m  %_directory%\%_fname%
	move *.a52  %_directory%\%_fname%
	move *.aa  %_directory%\%_fname%
	move *.aa3  %_directory%\%_fname%
	move *.aac  %_directory%\%_fname%
	move *.aax  %_directory%\%_fname%
	move *.ab  %_directory%\%_fname%
	move *.abc  %_directory%\%_fname%
	move *.abm  %_directory%\%_fname%
	move *.ac3  %_directory%\%_fname%
	move *.acd  %_directory%\%_fname%
	move *.acd-bak  %_directory%\%_fname%
	move *.acd-zip  %_directory%\%_fname%
	move *.acm  %_directory%\%_fname%
	move *.acp  %_directory%\%_fname%
	move *.act  %_directory%\%_fname%
	move *.adg  %_directory%\%_fname%
	move *.adt  %_directory%\%_fname%
	move *.adts  %_directory%\%_fname%
	move *.adv  %_directory%\%_fname%
	move *.afc  %_directory%\%_fname%
	move *.agm  %_directory%\%_fname%
	move *.agr  %_directory%\%_fname%
	move *.ahx  %_directory%\%_fname%
	move *.aif  %_directory%\%_fname%
	move *.aifc  %_directory%\%_fname%
	move *.aiff  %_directory%\%_fname%
	move *.ais  %_directory%\%_fname%
	move *.akp  %_directory%\%_fname%
	move *.al  %_directory%\%_fname%
	move *.alac  %_directory%\%_fname%
	move *.alaw  %_directory%\%_fname%
	move *.alc  %_directory%\%_fname%
	move *.all  %_directory%\%_fname%
	move *.als  %_directory%\%_fname%
	move *.amf  %_directory%\%_fname%
	move *.amr  %_directory%\%_fname%
	move *.ams  %_directory%\%_fname%
	move *.ams  %_directory%\%_fname%
	move *.amxd  %_directory%\%_fname%
	move *.aob  %_directory%\%_fname%
	move *.ape  %_directory%\%_fname%
	move *.apf  %_directory%\%_fname%
	move *.apl  %_directory%\%_fname%
	move *.aria  %_directory%\%_fname%
	move *.ariax  %_directory%\%_fname%
	move *.asd  %_directory%\%_fname%
	move *.ase  %_directory%\%_fname%
	move *.at3  %_directory%\%_fname%
	move *.atrac  %_directory%\%_fname%
	move *.au  %_directory%\%_fname%
	move *.au  %_directory%\%_fname%
	move *.aud  %_directory%\%_fname%
	move *.aup  %_directory%\%_fname%
	move *.avastsounds  %_directory%\%_fname%
	move *.avr  %_directory%\%_fname%
	move *.awb  %_directory%\%_fname%
	move *.ay  %_directory%\%_fname%
	move *.b4s  %_directory%\%_fname%
	move *.band  %_directory%\%_fname%
	move *.bap  %_directory%\%_fname%
	move *.bcs  %_directory%\%_fname%
	move *.bdd  %_directory%\%_fname%
	move *.bidule  %_directory%\%_fname%
	move *.box  %_directory%\%_fname%
	move *.brstm  %_directory%\%_fname%
	move *.bun  %_directory%\%_fname%
	move *.bwf  %_directory%\%_fname%
	move *.bww  %_directory%\%_fname%
	move *.c01  %_directory%\%_fname%
	move *.caf  %_directory%\%_fname%
	move *.caff  %_directory%\%_fname%
	move *.cda  %_directory%\%_fname%
	move *.cdda  %_directory%\%_fname%
	move *.cdlx  %_directory%\%_fname%
	move *.cdo  %_directory%\%_fname%
	move *.cdr  %_directory%\%_fname%
	move *.cel  %_directory%\%_fname%
	move *.cfa  %_directory%\%_fname%
	move *.cfxr  %_directory%\%_fname%
	move *.cidb  %_directory%\%_fname%
	move *.cmf  %_directory%\%_fname%
	move *.copy  %_directory%\%_fname%
	move *.cpr  %_directory%\%_fname%
	move *.cpt  %_directory%\%_fname%
	move *.csh  %_directory%\%_fname%
	move *.cts  %_directory%\%_fname%
	move *.cwp  %_directory%\%_fname%
	move *.d00  %_directory%\%_fname%
	echo 20% done
	move *.d01  %_directory%\%_fname%
	move *.dcf  %_directory%\%_fname%
	move *.dcm  %_directory%\%_fname%
	move *.dct  %_directory%\%_fname%
	move *.ddt  %_directory%\%_fname%
	move *.dewf  %_directory%\%_fname%
	move *.df2  %_directory%\%_fname%
	move *.dfc  %_directory%\%_fname%
	move *.dig  %_directory%\%_fname%
	move *.dig  %_directory%\%_fname%
	move *.djr  %_directory%\%_fname%
	move *.dls  %_directory%\%_fname%
	move *.dm  %_directory%\%_fname%
	move *.dmf  %_directory%\%_fname%
	move *.dmsa  %_directory%\%_fname%
	move *.dmse  %_directory%\%_fname%
	move *.dra  %_directory%\%_fname%
	move *.drg  %_directory%\%_fname%
	move *.ds  %_directory%\%_fname%
	move *.ds2  %_directory%\%_fname%
	move *.dsf  %_directory%\%_fname%
	move *.dsm  %_directory%\%_fname%
	move *.dsp  %_directory%\%_fname%
	move *.dss  %_directory%\%_fname%
	move *.dtm  %_directory%\%_fname%
	move *.dts  %_directory%\%_fname%
	move *.dtshd  %_directory%\%_fname%
	move *.dvf  %_directory%\%_fname%
	move *.dwa  %_directory%\%_fname%
	move *.dwd  %_directory%\%_fname%
	move *.ear  %_directory%\%_fname%
	move *.efa  %_directory%\%_fname%
	move *.efe  %_directory%\%_fname%
	move *.efk  %_directory%\%_fname%
	move *.efq  %_directory%\%_fname%
	move *.efs  %_directory%\%_fname%
	move *.efv  %_directory%\%_fname%
	move *.emd  %_directory%\%_fname%
	move *.emp  %_directory%\%_fname%
	move *.emx  %_directory%\%_fname%
	move *.emy  %_directory%\%_fname%
	move *.esps  %_directory%\%_fname%
	move *.expressionmap  %_directory%\%_fname%
	move *.f2r  %_directory%\%_fname%
	move *.f32  %_directory%\%_fname%
	move *.f3r  %_directory%\%_fname%
	move *.f4a  %_directory%\%_fname%
	move *.f64  %_directory%\%_fname%
	move *.far  %_directory%\%_fname%
	move *.fda  %_directory%\%_fname%
	move *.fdp  %_directory%\%_fname%
	move *.fev  %_directory%\%_fname%
	move *.fff  %_directory%\%_fname%
	move *.flac  %_directory%\%_fname%
	move *.flp  %_directory%\%_fname%
	move *.fls  %_directory%\%_fname%
	move *.frg  %_directory%\%_fname%
	move *.fsb  %_directory%\%_fname%
	move *.fsm  %_directory%\%_fname%
	move *.ftm  %_directory%\%_fname%
	move *.fzb  %_directory%\%_fname%
	move *.fzf  %_directory%\%_fname%
	move *.fzv  %_directory%\%_fname%
	move *.g721  %_directory%\%_fname%
	move *.g723  %_directory%\%_fname%
	move *.g726  %_directory%\%_fname%
	move *.gbproj  %_directory%\%_fname%
	move *.gbs  %_directory%\%_fname%
	move *.gig  %_directory%\%_fname%
	move *.gio  %_directory%\%_fname%
	move *.gio  %_directory%\%_fname%
	move *.gm  %_directory%\%_fname%
	move *.gp5  %_directory%\%_fname%
	move *.gpbank  %_directory%\%_fname%
	move *.gpk  %_directory%\%_fname%
	move *.gpx  %_directory%\%_fname%
	move *.gro  %_directory%\%_fname%
	move *.groove  %_directory%\%_fname%
	move *.gsm  %_directory%\%_fname%
	move *.gsm  %_directory%\%_fname%
	move *.h0  %_directory%\%_fname%
	move *.hdp  %_directory%\%_fname%
	move *.hma  %_directory%\%_fname%
	move *.hmi  %_directory%\%_fname%
	move *.hsb  %_directory%\%_fname%
	move *.ics  %_directory%\%_fname%
	move *.iff  %_directory%\%_fname%
	move *.igp  %_directory%\%_fname%
	move *.igr  %_directory%\%_fname%
	move *.imf  %_directory%\%_fname%
	move *.imp  %_directory%\%_fname%
	move *.ins  %_directory%\%_fname%
	move *.ins  %_directory%\%_fname%
	move *.isma  %_directory%\%_fname%
	move *.it  %_directory%\%_fname%
	move *.iti  %_directory%\%_fname%
	move *.its  %_directory%\%_fname%
	move *.jam  %_directory%\%_fname%
	move *.jam  %_directory%\%_fname%
	move *.jo  %_directory%\%_fname%
	move *.jo-7z  %_directory%\%_fname%
	move *.k25  %_directory%\%_fname%
	move *.k26  %_directory%\%_fname%
	move *.kar  %_directory%\%_fname%
	move *.kfn  %_directory%\%_fname%
	move *.kin  %_directory%\%_fname%
	move *.kit  %_directory%\%_fname%
	move *.kmp  %_directory%\%_fname%
	move *.koz  %_directory%\%_fname%
	move *.koz  %_directory%\%_fname%
	move *.kpl  %_directory%\%_fname%
	move *.krz  %_directory%\%_fname%
	move *.ksc  %_directory%\%_fname%
	move *.ksf  %_directory%\%_fname%
	move *.ksm  %_directory%\%_fname%
	move *.kt2  %_directory%\%_fname%
	move *.kt3  %_directory%\%_fname%
	move *.ktp  %_directory%\%_fname%
	move *.l  %_directory%\%_fname%
	move *.la  %_directory%\%_fname%
	move *.lof  %_directory%\%_fname%
	move *.logic  %_directory%\%_fname%
	move *.lqt  %_directory%\%_fname%
	move *.lso  %_directory%\%_fname%
	move *.lvp  %_directory%\%_fname%
	move *.lwv  %_directory%\%_fname%
	move *.m1a  %_directory%\%_fname%
	move *.m3u  %_directory%\%_fname%
	move *.m3u8  %_directory%\%_fname%
	move *.m4a  %_directory%\%_fname%
	move *.m4b  %_directory%\%_fname%
	move *.m4p  %_directory%\%_fname%
	move *.m4r  %_directory%\%_fname%
	move *.ma1  %_directory%\%_fname%
	move *.mbr  %_directory%\%_fname%
	move *.mdl  %_directory%\%_fname%
	move *.med  %_directory%\%_fname%
	move *.mgv  %_directory%\%_fname%
	move *.mid  %_directory%\%_fname%
	move *.midi  %_directory%\%_fname%
	move *.miniusf  %_directory%\%_fname%
	move *.mka  %_directory%\%_fname%
	move *.mlp  %_directory%\%_fname%
	move *.mmf  %_directory%\%_fname%
	move *.mmm  %_directory%\%_fname%
	move *.mmp  %_directory%\%_fname%
	move *.mo3  %_directory%\%_fname%
	move *.mod  %_directory%\%_fname%
	move *.mp1  %_directory%\%_fname%
	move *.mp2  %_directory%\%_fname%
	move *.mp3  %_directory%\%_fname%
	pause
	move *.mpa  %_directory%\%_fname%
	move *.mpc  %_directory%\%_fname%
	move *.mpga  %_directory%\%_fname%
	move *.mpu  %_directory%\%_fname%
	move *.mp_  %_directory%\%_fname%
	move *.mscx  %_directory%\%_fname%
	move *.mscz  %_directory%\%_fname%
	move *.msv  %_directory%\%_fname%
	move *.mt2  %_directory%\%_fname%
	move *.mt9  %_directory%\%_fname%
	move *.mte  %_directory%\%_fname%
	move *.mtf  %_directory%\%_fname%
	move *.mti  %_directory%\%_fname%
	move *.mtm  %_directory%\%_fname%
	move *.mtp  %_directory%\%_fname%
	move *.mts  %_directory%\%_fname%
	move *.mu3  %_directory%\%_fname%
	move *.mui  %_directory%\%_fname%
	move *.mus  %_directory%\%_fname%
	move *.mus  %_directory%\%_fname%
	move *.mus  %_directory%\%_fname%
	move *.musa  %_directory%\%_fname%
	move *.mux  %_directory%\%_fname%
	move *.mux  %_directory%\%_fname%
	move *.muz  %_directory%\%_fname%
	move *.mws  %_directory%\%_fname%
	move *.mx3  %_directory%\%_fname%
	move *.mx4  %_directory%\%_fname%
	move *.mx5  %_directory%\%_fname%
	move *.mx5template  %_directory%\%_fname%
	move *.mxl  %_directory%\%_fname%
	move *.mxmf  %_directory%\%_fname%
	move *.myr  %_directory%\%_fname%
	move *.mzp  %_directory%\%_fname%
	move *.nap  %_directory%\%_fname%
	move *.nbs  %_directory%\%_fname%
	move *.ncw  %_directory%\%_fname%
	move *.nkb  %_directory%\%_fname%
	move *.nkc  %_directory%\%_fname%
	move *.nki  %_directory%\%_fname%
	move *.nkm  %_directory%\%_fname%
	move *.nks  %_directory%\%_fname%
	move *.nkx  %_directory%\%_fname%
	move *.npl  %_directory%\%_fname%
	move *.nra  %_directory%\%_fname%
	move *.nrt  %_directory%\%_fname%
	move *.nsa  %_directory%\%_fname%
	move *.nsf  %_directory%\%_fname%
	move *.nst  %_directory%\%_fname%
	move *.ntn  %_directory%\%_fname%
	move *.nvf  %_directory%\%_fname%
	move *.nwc  %_directory%\%_fname%
	move *.odm  %_directory%\%_fname%
	echo 40% done
	move *.ofr  %_directory%\%_fname%
	move *.oga  %_directory%\%_fname%
	move *.ogg  %_directory%\%_fname%
	move *.okt  %_directory%\%_fname%
	move *.oma  %_directory%\%_fname%
	move *.omf  %_directory%\%_fname%
	move *.omg  %_directory%\%_fname%
	move *.omx  %_directory%\%_fname%
	move *.orc  %_directory%\%_fname%
	move *.ots  %_directory%\%_fname%
	move *.ove  %_directory%\%_fname%
	move *.ovw  %_directory%\%_fname%
	move *.ovw  %_directory%\%_fname%
	move *.pac  %_directory%\%_fname%
	move *.pat  %_directory%\%_fname%
	move *.pbf  %_directory%\%_fname%
	move *.pca  %_directory%\%_fname%
	move *.pcast  %_directory%\%_fname%
	move *.pcg  %_directory%\%_fname%
	move *.pcm  %_directory%\%_fname%
	move *.pd  %_directory%\%_fname%
	move *.peak  %_directory%\%_fname%
	move *.pek  %_directory%\%_fname%
	move *.pho  %_directory%\%_fname%
	move *.phy  %_directory%\%_fname%
	move *.pk  %_directory%\%_fname%
	move *.pkf  %_directory%\%_fname%
	move *.pla  %_directory%\%_fname%
	move *.pls  %_directory%\%_fname%
	move *.plst  %_directory%\%_fname%
	move *.ply  %_directory%\%_fname%
	move *.pna  %_directory%\%_fname%
	move *.pno  %_directory%\%_fname%
	move *.ppc  %_directory%\%_fname%
	move *.ppcx  %_directory%\%_fname%
	move *.prg  %_directory%\%_fname%
	move *.prg  %_directory%\%_fname%
	move *.psf  %_directory%\%_fname%
	move *.psm  %_directory%\%_fname%
	move *.psy  %_directory%\%_fname%
	move *.ptf  %_directory%\%_fname%
	move *.ptm  %_directory%\%_fname%
	move *.pts  %_directory%\%_fname%
	move *.pvc  %_directory%\%_fname%
	move *.qcp  %_directory%\%_fname%
	move *.r  %_directory%\%_fname%
	move *.r1m  %_directory%\%_fname%
	move *.ra  %_directory%\%_fname%
	move *.ram  %_directory%\%_fname%
	move *.raw  %_directory%\%_fname%
	move *.rax  %_directory%\%_fname%
	move *.rbs  %_directory%\%_fname%
	move *.rbs  %_directory%\%_fname%
	move *.rcy  %_directory%\%_fname%
	move *.record  %_directory%\%_fname%
	move *.rex  %_directory%\%_fname%
	move *.rfl  %_directory%\%_fname%
	move *.rip  %_directory%\%_fname%
	move *.rmf  %_directory%\%_fname%
	move *.rmi  %_directory%\%_fname%
	move *.rmj  %_directory%\%_fname%
	move *.rmm  %_directory%\%_fname%
	move *.rmx  %_directory%\%_fname%
	move *.rng  %_directory%\%_fname%
	move *.rns  %_directory%\%_fname%
	move *.rol  %_directory%\%_fname%
	move *.rsn  %_directory%\%_fname%
	move *.rso  %_directory%\%_fname%
	move *.rti  %_directory%\%_fname%
	move *.rtm  %_directory%\%_fname%
	move *.rts  %_directory%\%_fname%
	move *.rvx  %_directory%\%_fname%
	move *.rx2  %_directory%\%_fname%
	move *.s3i  %_directory%\%_fname%
	move *.s3m  %_directory%\%_fname%
	move *.s3z  %_directory%\%_fname%
	move *.saf  %_directory%\%_fname%
	move *.sam  %_directory%\%_fname%
	move *.sap  %_directory%\%_fname%
	move *.sb  %_directory%\%_fname%
	move *.sbg  %_directory%\%_fname%
	move *.sbi  %_directory%\%_fname%
	move *.sbk  %_directory%\%_fname%
	move *.sc2  %_directory%\%_fname%
	move *.sd  %_directory%\%_fname%
	move *.sd  %_directory%\%_fname%
	move *.sd2  %_directory%\%_fname%
	move *.sd2f  %_directory%\%_fname%
	move *.sdat  %_directory%\%_fname%
	move *.sdii  %_directory%\%_fname%
	move *.sds  %_directory%\%_fname%
	move *.sdt  %_directory%\%_fname%
	move *.sdx  %_directory%\%_fname%
	move *.seg  %_directory%\%_fname%
	move *.seq  %_directory%\%_fname%
	move *.ses  %_directory%\%_fname%
	move *.sesx  %_directory%\%_fname%
	move *.sf  %_directory%\%_fname%
	move *.sf2  %_directory%\%_fname%
	move *.sfap0  %_directory%\%_fname%
	move *.sfk  %_directory%\%_fname%
	move *.sfl  %_directory%\%_fname%
	move *.sfs  %_directory%\%_fname%
	move *.shn  %_directory%\%_fname%
	move *.sib  %_directory%\%_fname%
	move *.sid  %_directory%\%_fname%
	move *.slp  %_directory%\%_fname%
	move *.slx  %_directory%\%_fname%
	move *.sma  %_directory%\%_fname%
	move *.smf  %_directory%\%_fname%
	move *.smp  %_directory%\%_fname%
	move *.smp  %_directory%\%_fname%
	move *.snd  %_directory%\%_fname%
	move *.snd  %_directory%\%_fname%
	move *.snd  %_directory%\%_fname%
	move *.sng  %_directory%\%_fname%
	move *.sng  %_directory%\%_fname%
	move *.sou  %_directory%\%_fname%
	move *.sph  %_directory%\%_fname%
	move *.sppack  %_directory%\%_fname%
	move *.sprg  %_directory%\%_fname%
	move *.spx  %_directory%\%_fname%
	move *.sseq  %_directory%\%_fname%
	move *.sseq  %_directory%\%_fname%
	move *.ssnd  %_directory%\%_fname%
	move *.stap  %_directory%\%_fname%
	move *.stm  %_directory%\%_fname%
	move *.stx  %_directory%\%_fname%
	move *.sty  %_directory%\%_fname%
	move *.sty  %_directory%\%_fname%
	move *.svd  %_directory%\%_fname%
	move *.svx  %_directory%\%_fname%
	move *.sw  %_directory%\%_fname%
	move *.swa  %_directory%\%_fname%
	move *.sxt  %_directory%\%_fname%
	move *.syh  %_directory%\%_fname%
	move *.syn  %_directory%\%_fname%
	move *.syn  %_directory%\%_fname%
	move *.syw  %_directory%\%_fname%
	echo 60% done
	move *.syx  %_directory%\%_fname%
	move *.tak  %_directory%\%_fname%
	move *.tak  %_directory%\%_fname%
	move *.td0  %_directory%\%_fname%
	move *.tfmx  %_directory%\%_fname%
	move *.tg  %_directory%\%_fname%
	move *.thx  %_directory%\%_fname%
	move *.toc  %_directory%\%_fname%
	move *.tsp  %_directory%\%_fname%
	move *.tta  %_directory%\%_fname%
	move *.tun  %_directory%\%_fname%
	move *.txw  %_directory%\%_fname%
	move *.u  %_directory%\%_fname%
	move *.u8  %_directory%\%_fname%
	move *.uax  %_directory%\%_fname%
	move *.ub  %_directory%\%_fname%
	move *.ulaw  %_directory%\%_fname%
	move *.ult  %_directory%\%_fname%
	move *.ulw  %_directory%\%_fname%
	move *.uni  %_directory%\%_fname%
	move *.usf  %_directory%\%_fname%
	move *.usflib  %_directory%\%_fname%
	move *.uw  %_directory%\%_fname%
	move *.uwf  %_directory%\%_fname%
	move *.v2m  %_directory%\%_fname%
	move *.vag  %_directory%\%_fname%
	move *.val  %_directory%\%_fname%
	move *.vap  %_directory%\%_fname%
	move *.vb  %_directory%\%_fname%
	move *.vc3  %_directory%\%_fname%
	move *.vdj  %_directory%\%_fname%
	move *.vgm  %_directory%\%_fname%
	move *.vgz  %_directory%\%_fname%
	move *.vlc  %_directory%\%_fname%
	move *.vmd  %_directory%\%_fname%
	move *.vmf  %_directory%\%_fname%
	move *.vmf  %_directory%\%_fname%
	move *.vmo  %_directory%\%_fname%
	move *.voc  %_directory%\%_fname%
	move *.voi  %_directory%\%_fname%
	move *.vox  %_directory%\%_fname%
	move *.vpm  %_directory%\%_fname%
	move *.vqf  %_directory%\%_fname%
	move *.vrf  %_directory%\%_fname%
	move *.vsq  %_directory%\%_fname%
	move *.vtx  %_directory%\%_fname%
	move *.vyf  %_directory%\%_fname%
	move *.w01  %_directory%\%_fname%
	move *.w64  %_directory%\%_fname%
	move *.wav  %_directory%\%_fname%
	move *.wav  %_directory%\%_fname%
	move *.wave  %_directory%\%_fname%
	move *.wax  %_directory%\%_fname%
	move *.wem  %_directory%\%_fname%
	move *.wfb  %_directory%\%_fname%
	move *.wfd  %_directory%\%_fname%
	move *.wfp  %_directory%\%_fname%
	move *.wma  %_directory%\%_fname%
	move *.wow  %_directory%\%_fname%
	move *.wpk  %_directory%\%_fname%
	move *.wpp  %_directory%\%_fname%
	move *.wproj  %_directory%\%_fname%
	move *.wrk  %_directory%\%_fname%
	move *.wtpl  %_directory%\%_fname%
	move *.wtpt  %_directory%\%_fname%
	move *.wus  %_directory%\%_fname%
	move *.wut  %_directory%\%_fname%
	move *.wv  %_directory%\%_fname%
	move *.wvc  %_directory%\%_fname%
	move *.wve  %_directory%\%_fname%
	move *.wwu  %_directory%\%_fname%
	move *.wyz  %_directory%\%_fname%
	move *.xa  %_directory%\%_fname%
	move *.xa  %_directory%\%_fname%
	move *.xfs  %_directory%\%_fname%
	move *.xi  %_directory%\%_fname%
	echo 80% done
	move *.xm  %_directory%\%_fname%
	move *.xmf  %_directory%\%_fname%
	move *.xmi  %_directory%\%_fname%
	move *.xmz  %_directory%\%_fname%
	move *.xp  %_directory%\%_fname%
	move *.xrns  %_directory%\%_fname%
	move *.xsb  %_directory%\%_fname%
	move *.xspf  %_directory%\%_fname%
	move *.xt  %_directory%\%_fname%
	move *.xwb  %_directory%\%_fname%
	move *.ym  %_directory%\%_fname%
	move *.zpa  %_directory%\%_fname%
	move *.zpl  %_directory%\%_fname%
	move *.zvd  %_directory%\%_fname%
	move *.zvr  %_directory%\%_fname%
		goto end
::____________________________________________done_________________
:image
	cd /D %_directory%
	mkdir %_fname%
	move *.001  %_directory%\%_fname%
	move *.2bp  %_directory%\%_fname%
	move *.36  %_directory%\%_fname%
	move *.3fr  %_directory%\%_fname%
	move *.411  %_directory%\%_fname%
	move *.73i  %_directory%\%_fname%
	move *.8pbs  %_directory%\%_fname%
	move *.8xi  %_directory%\%_fname%
	move *.abm  %_directory%\%_fname%
	move *.acorn  %_directory%\%_fname%
	move *.acr  %_directory%\%_fname%
	move *.adc  %_directory%\%_fname%
	move *.afx  %_directory%\%_fname%
	move *.agif  %_directory%\%_fname%
	move *.agp  %_directory%\%_fname%
	move *.aic  %_directory%\%_fname%
	move *.ais  %_directory%\%_fname%
	move *.albm  %_directory%\%_fname%
	move *.apd  %_directory%\%_fname%
	move *.apm  %_directory%\%_fname%
	move *.apng  %_directory%\%_fname%
	move *.aps  %_directory%\%_fname%
	move *.apx  %_directory%\%_fname%
	move *.ari  %_directory%\%_fname%
	move *.arr  %_directory%\%_fname%
	move *.art  %_directory%\%_fname%
	move *.artwork  %_directory%\%_fname%
	move *.arw  %_directory%\%_fname%
	move *.arw  %_directory%\%_fname%
	move *.asw  %_directory%\%_fname%
	move *.avatar  %_directory%\%_fname%
	move *.awd  %_directory%\%_fname%
	move *.awd  %_directory%\%_fname%
	move *.bay  %_directory%\%_fname%
	move *.blkrt  %_directory%\%_fname%
	move *.blz  %_directory%\%_fname%
	move *.bm2  %_directory%\%_fname%
	move *.bmc  %_directory%\%_fname%
	move *.bmf  %_directory%\%_fname%
	move *.bmp  %_directory%\%_fname%
	move *.bmx  %_directory%\%_fname%
	move *.bmz  %_directory%\%_fname%
	move *.brk  %_directory%\%_fname%
	move *.brn  %_directory%\%_fname%
	move *.brt  %_directory%\%_fname%
	move *.bss  %_directory%\%_fname%
	move *.bti  %_directory%\%_fname%
	move *.c4  %_directory%\%_fname%
	move *.cal  %_directory%\%_fname%
	move *.cals  %_directory%\%_fname%
	move *.cam  %_directory%\%_fname%
	move *.can  %_directory%\%_fname%
	move *.cd5  %_directory%\%_fname%
	move *.cdc  %_directory%\%_fname%
	move *.cdg  %_directory%\%_fname%
	move *.ce  %_directory%\%_fname%
	move *.cimg  %_directory%\%_fname%
	move *.cin  %_directory%\%_fname%
	move *.cit  %_directory%\%_fname%
	move *.colz  %_directory%\%_fname%
	move *.cpc  %_directory%\%_fname%
	move *.cpd  %_directory%\%_fname%
	move *.cpg  %_directory%\%_fname%
	move *.cps  %_directory%\%_fname%
	move *.cpt  %_directory%\%_fname%
	move *.cpx  %_directory%\%_fname%
	move *.cr2  %_directory%\%_fname%
	move *.crw  %_directory%\%_fname%
	move *.csf  %_directory%\%_fname%
	move *.ct  %_directory%\%_fname%
	move *.cut  %_directory%\%_fname%
	move *.dc2  %_directory%\%_fname%
	move *.dcm  %_directory%\%_fname%
	move *.dcr  %_directory%\%_fname%
	move *.dcx  %_directory%\%_fname%
	move *.ddb  %_directory%\%_fname%
	move *.dds  %_directory%\%_fname%
	move *.ddt  %_directory%\%_fname%
	move *.dib  %_directory%\%_fname%
	move *.dicom  %_directory%\%_fname%
	move *.djv  %_directory%\%_fname%
	move *.djvu  %_directory%\%_fname%
	move *.dm3  %_directory%\%_fname%
	move *.dng  %_directory%\%_fname%
	move *.dpx  %_directory%\%_fname%
	move *.drz  %_directory%\%_fname%
	move *.dt2  %_directory%\%_fname%
	move *.dtw  %_directory%\%_fname%
	move *.dvl  %_directory%\%_fname%
	move *.ecw  %_directory%\%_fname%
	move *.epp  %_directory%\%_fname%
	move *.erf  %_directory%\%_fname%
	move *.exr  %_directory%\%_fname%
	move *.fac  %_directory%\%_fname%
	move *.face  %_directory%\%_fname%
	move *.fal  %_directory%\%_fname%
	move *.fax  %_directory%\%_fname%
	move *.fbm  %_directory%\%_fname%
	move *.fff  %_directory%\%_fname%
	move *.fil  %_directory%\%_fname%
	move *.fits  %_directory%\%_fname%
	move *.fpg  %_directory%\%_fname%
	move *.fpos  %_directory%\%_fname%
	move *.fpx  %_directory%\%_fname%
	move *.frm  %_directory%\%_fname%
	move *.g3  %_directory%\%_fname%
	move *.gbr  %_directory%\%_fname%
	move *.gcdp  %_directory%\%_fname%
	move *.gfb  %_directory%\%_fname%
	move *.gfie  %_directory%\%_fname%
	move *.gif  %_directory%\%_fname%
	move *.gih  %_directory%\%_fname%
	move *.gim  %_directory%\%_fname%
	move *.gmbck  %_directory%\%_fname%
	move *.gmspr  %_directory%\%_fname%
	move *.gp4  %_directory%\%_fname%
	move *.gpd  %_directory%\%_fname%
	move *.gro  %_directory%\%_fname%
	move *.grob  %_directory%\%_fname%
	move *.gry  %_directory%\%_fname%
	move *.hdp  %_directory%\%_fname%
	move *.hdr  %_directory%\%_fname%
	move *.hf  %_directory%\%_fname%
	move *.hpi  %_directory%\%_fname%
	move *.hr  %_directory%\%_fname%
	move *.hrf  %_directory%\%_fname%
	move *.i3d  %_directory%\%_fname%
	move *.ic1  %_directory%\%_fname%
	move *.ic2  %_directory%\%_fname%
	move *.ic3  %_directory%\%_fname%
	move *.ica  %_directory%\%_fname%
	move *.icb  %_directory%\%_fname%
	move *.icn  %_directory%\%_fname%
	move *.icon  %_directory%\%_fname%
	move *.icpr  %_directory%\%_fname%
	move *.iiq  %_directory%\%_fname%
	move *.ilbm  %_directory%\%_fname%
	move *.img  %_directory%\%_fname%
	move *.imj  %_directory%\%_fname%
	move *.info  %_directory%\%_fname%
	move *.ink  %_directory%\%_fname%
	move *.int  %_directory%\%_fname%
	move *.ipx  %_directory%\%_fname%
	move *.itc2  %_directory%\%_fname%
	move *.ithmb  %_directory%\%_fname%
	move *.ivr  %_directory%\%_fname%
	move *.ivue  %_directory%\%_fname%
	move *.iwi  %_directory%\%_fname%
	move *.j  %_directory%\%_fname%
	move *.j2c  %_directory%\%_fname%
	move *.j2k  %_directory%\%_fname%
	move *.jas  %_directory%\%_fname%
	move *.jb2  %_directory%\%_fname%
	move *.jbf  %_directory%\%_fname%
	move *.jbig  %_directory%\%_fname%
	move *.jbig2  %_directory%\%_fname%
	move *.jbmp  %_directory%\%_fname%
	move *.jbr  %_directory%\%_fname%
	move *.jfi  %_directory%\%_fname%
	move *.jfif  %_directory%\%_fname%
	move *.jia  %_directory%\%_fname%
	move *.jif  %_directory%\%_fname%
	move *.jiff  %_directory%\%_fname%
	move *.jng  %_directory%\%_fname%
	move *.jp2  %_directory%\%_fname%
	move *.jpc  %_directory%\%_fname%
	move *.jpd  %_directory%\%_fname%
	move *.jpe  %_directory%\%_fname%
	move *.jpeg  %_directory%\%_fname%
	move *.jpf  %_directory%\%_fname%
	move *.jpg  %_directory%\%_fname%

	move *.jpg2  %_directory%\%_fname%
	move *.jps  %_directory%\%_fname%
	move *.jpx  %_directory%\%_fname%
	move *.jtf  %_directory%\%_fname%
	move *.jwl  %_directory%\%_fname%
	move *.jxr  %_directory%\%_fname%
	move *.kdc  %_directory%\%_fname%
	move *.kdi  %_directory%\%_fname%
	move *.kdk  %_directory%\%_fname%
	move *.kfx  %_directory%\%_fname%
	move *.kic  %_directory%\%_fname%
	move *.kodak  %_directory%\%_fname%
	move *.kpg  %_directory%\%_fname%
	move *.lbm  %_directory%\%_fname%
	move *.lif  %_directory%\%_fname%
	move *.ljp  %_directory%\%_fname%
	move *.mac  %_directory%\%_fname%
	move *.mat  %_directory%\%_fname%
	move *.max  %_directory%\%_fname%
	move *.mbm  %_directory%\%_fname%
	move *.mcs  %_directory%\%_fname%
	move *.mef  %_directory%\%_fname%
	move *.met  %_directory%\%_fname%
	move *.mic  %_directory%\%_fname%
	move *.mip  %_directory%\%_fname%
	move *.mix  %_directory%\%_fname%
	move *.mng  %_directory%\%_fname%
	move *.mnr  %_directory%\%_fname%
	move *.mos  %_directory%\%_fname%
	move *.mpf  %_directory%\%_fname%
	move *.mpo  %_directory%\%_fname%
	move *.mrb  %_directory%\%_fname%
	move *.mrw  %_directory%\%_fname%
	move *.mrxs  %_directory%\%_fname%
	move *.msk  %_directory%\%_fname%
	move *.msp  %_directory%\%_fname%
	move *.mxi  %_directory%\%_fname%
	move *.myl  %_directory%\%_fname%
	move *.ncd  %_directory%\%_fname%
	move *.ncr  %_directory%\%_fname%
	move *.nct  %_directory%\%_fname%
	move *.nef  %_directory%\%_fname%
	move *.neo  %_directory%\%_fname%
	move *.nrw  %_directory%\%_fname%
	move *.oc3  %_directory%\%_fname%
	move *.oc4  %_directory%\%_fname%
	move *.oc5  %_directory%\%_fname%
	move *.oci  %_directory%\%_fname%
	move *.odi  %_directory%\%_fname%
	move *.omf  %_directory%\%_fname%
	move *.orf  %_directory%\%_fname%
	move *.ota  %_directory%\%_fname%
	move *.otb  %_directory%\%_fname%
	move *.oti  %_directory%\%_fname%
	move *.pac  %_directory%\%_fname%
	move *.pal  %_directory%\%_fname%
	move *.pap  %_directory%\%_fname%
	move *.pat  %_directory%\%_fname%
	move *.pbm  %_directory%\%_fname%
	move *.pc1  %_directory%\%_fname%
	move *.pc2  %_directory%\%_fname%
	move *.pc3  %_directory%\%_fname%
	move *.pcd  %_directory%\%_fname%
	move *.pcx  %_directory%\%_fname%
	move *.pdd  %_directory%\%_fname%
	move *.pdn  %_directory%\%_fname%
	move *.pe4  %_directory%\%_fname%
	move *.pe4  %_directory%\%_fname%
	move *.pef  %_directory%\%_fname%
	move *.pfi  %_directory%\%_fname%
	move *.pfr  %_directory%\%_fname%
	move *.pgf  %_directory%\%_fname%
	move *.pgm  %_directory%\%_fname%
	move *.pi1  %_directory%\%_fname%
	move *.pi2  %_directory%\%_fname%
	move *.pi2  %_directory%\%_fname%
	move *.pi3  %_directory%\%_fname%
	move *.pi4  %_directory%\%_fname%
	move *.pi5  %_directory%\%_fname%
	move *.pi6  %_directory%\%_fname%
	move *.pic  %_directory%\%_fname%
	move *.pic  %_directory%\%_fname%
	move *.pic  %_directory%\%_fname%
	move *.picnc  %_directory%\%_fname%
	move *.pict  %_directory%\%_fname%
	move *.pictclipping  %_directory%\%_fname%
	move *.pix  %_directory%\%_fname%
	move *.pix  %_directory%\%_fname%
	move *.pixadex  %_directory%\%_fname%
	move *.pjpeg  %_directory%\%_fname%
	move *.pjpg  %_directory%\%_fname%
	move *.pm  %_directory%\%_fname%
	move *.pm3  %_directory%\%_fname%
	move *.pmg  %_directory%\%_fname%
	move *.png  %_directory%\%_fname%
	move *.pni  %_directory%\%_fname%
	move *.pnm  %_directory%\%_fname%
	move *.pns  %_directory%\%_fname%
	move *.pnt  %_directory%\%_fname%
	move *.pntg  %_directory%\%_fname%
	move *.pop  %_directory%\%_fname%
	move *.pov  %_directory%\%_fname%
	move *.pov  %_directory%\%_fname%
	move *.pp4  %_directory%\%_fname%
	move *.pp5  %_directory%\%_fname%
	move *.ppf  %_directory%\%_fname%
	move *.ppm  %_directory%\%_fname%
	move *.prw  %_directory%\%_fname%
	move *.psb  %_directory%\%_fname%
	move *.psd  %_directory%\%_fname%
	move *.psdx  %_directory%\%_fname%
	move *.pse  %_directory%\%_fname%
	move *.psf  %_directory%\%_fname%
	move *.psp  %_directory%\%_fname%
	move *.pspbrush  %_directory%\%_fname%
	move *.pspimage  %_directory%\%_fname%
	move *.ptg  %_directory%\%_fname%
	move *.ptk  %_directory%\%_fname%
	move *.ptx  %_directory%\%_fname%
	move *.ptx  %_directory%\%_fname%
	move *.pvr  %_directory%\%_fname%
	move *.pwp  %_directory%\%_fname%
	move *.px  %_directory%\%_fname%
	move *.pxd  %_directory%\%_fname%
	move *.pxicon  %_directory%\%_fname%
	move *.pxm  %_directory%\%_fname%
	move *.pxr  %_directory%\%_fname%
	move *.pzp  %_directory%\%_fname%
	move *.qif  %_directory%\%_fname%
	move *.qmg  %_directory%\%_fname%
	move *.qti  %_directory%\%_fname%
	move *.qtif  %_directory%\%_fname%
	move *.raf  %_directory%\%_fname%
	move *.ras  %_directory%\%_fname%
	move *.raw  %_directory%\%_fname%
	move *.rcl  %_directory%\%_fname%
	move *.rcu  %_directory%\%_fname%
	move *.rgb  %_directory%\%_fname%
	move *.rgb  %_directory%\%_fname%
	move *.ric  %_directory%\%_fname%
	move *.rif  %_directory%\%_fname%
	move *.riff  %_directory%\%_fname%
	move *.rix  %_directory%\%_fname%
	move *.rle  %_directory%\%_fname%
	move *.rli  %_directory%\%_fname%
	move *.rpf  %_directory%\%_fname%
	move *.rri  %_directory%\%_fname%
	move *.rs  %_directory%\%_fname%
	move *.rsb  %_directory%\%_fname%
	move *.rsr  %_directory%\%_fname%
	move *.rw2  %_directory%\%_fname%
	move *.rwl  %_directory%\%_fname%
	move *.s2mv  %_directory%\%_fname%
	move *.sar  %_directory%\%_fname%
	move *.sbp  %_directory%\%_fname%
	move *.scg  %_directory%\%_fname%
	move *.sci  %_directory%\%_fname%
	move *.scn  %_directory%\%_fname%
	move *.scp  %_directory%\%_fname%
	move *.sct  %_directory%\%_fname%
	move *.scu  %_directory%\%_fname%
	move *.sdr  %_directory%\%_fname%
	move *.sep  %_directory%\%_fname%
	move *.sfc  %_directory%\%_fname%
	move *.sff  %_directory%\%_fname%
	move *.sfw  %_directory%\%_fname%
	move *.sgi  %_directory%\%_fname%
	move *.shg  %_directory%\%_fname%
	move *.sid  %_directory%\%_fname%
	move *.sig  %_directory%\%_fname%
	move *.sim  %_directory%\%_fname%
	move *.skitch  %_directory%\%_fname%
	move *.skm  %_directory%\%_fname%
	move *.skypeemoticonset  %_directory%\%_fname%
	move *.sld  %_directory%\%_fname%
	move *.smp  %_directory%\%_fname%
	move *.sob  %_directory%\%_fname%
	move *.spa  %_directory%\%_fname%
	move *.spc  %_directory%\%_fname%
	move *.spe  %_directory%\%_fname%
	move *.sph  %_directory%\%_fname%
	move *.spiff  %_directory%\%_fname%
	move *.spj  %_directory%\%_fname%
	move *.spp  %_directory%\%_fname%
	move *.spr  %_directory%\%_fname%
	move *.sprite  %_directory%\%_fname%
	move *.spu  %_directory%\%_fname%
	move *.sr  %_directory%\%_fname%
	move *.sr2  %_directory%\%_fname%
	move *.srf  %_directory%\%_fname%
	move *.srw  %_directory%\%_fname%
	move *.ste  %_directory%\%_fname%
	move *.sumo  %_directory%\%_fname%
	move *.sun  %_directory%\%_fname%
	move *.suniff  %_directory%\%_fname%
	move *.sup  %_directory%\%_fname%
	move *.sva  %_directory%\%_fname%
	move *.t2b  %_directory%\%_fname%
	move *.taac  %_directory%\%_fname%
	move *.tb0  %_directory%\%_fname%
	move *.tbn  %_directory%\%_fname%
	move *.tex  %_directory%\%_fname%
	move *.tfc  %_directory%\%_fname%
	move *.tg4  %_directory%\%_fname%
	move *.tga  %_directory%\%_fname%
	move *.thm  %_directory%\%_fname%
	move *.thm  %_directory%\%_fname%
	move *.thumb  %_directory%\%_fname%
	move *.tif  %_directory%\%_fname%
	move *.tif  %_directory%\%_fname%
	move *.tiff  %_directory%\%_fname%
	move *.tjp  %_directory%\%_fname%
	move *.tn  %_directory%\%_fname%
	move *.tn1  %_directory%\%_fname%
	move *.tn2  %_directory%\%_fname%
	move *.tn3  %_directory%\%_fname%
	move *.tny  %_directory%\%_fname%
	move *.tpf  %_directory%\%_fname%
	move *.tpi  %_directory%\%_fname%
	move *.tps  %_directory%\%_fname%
	move *.trif  %_directory%\%_fname%
	move *.tub  %_directory%\%_fname%
	move *.u  %_directory%\%_fname%
	move *.ufo  %_directory%\%_fname%
	move *.urt  %_directory%\%_fname%
	move *.usertile-ms  %_directory%\%_fname%
	move *.v  %_directory%\%_fname%
	move *.vda  %_directory%\%_fname%
	move *.vff  %_directory%\%_fname%
	move *.vic  %_directory%\%_fname%
	move *.viff  %_directory%\%_fname%
	move *.vna  %_directory%\%_fname%
	move *.vss  %_directory%\%_fname%
	move *.vst  %_directory%\%_fname%
	move *.wb1  %_directory%\%_fname%
	move *.wbc  %_directory%\%_fname%
	move *.wbd  %_directory%\%_fname%
	move *.wbm  %_directory%\%_fname%
	move *.wbmp  %_directory%\%_fname%
	move *.wbz  %_directory%\%_fname%
	move *.wdp  %_directory%\%_fname%
	move *.webp  %_directory%\%_fname%
	move *.wi  %_directory%\%_fname%
	move *.wic  %_directory%\%_fname%
	move *.wmp  %_directory%\%_fname%
	move *.wpb  %_directory%\%_fname%
	move *.wpe  %_directory%\%_fname%
	move *.wvl  %_directory%\%_fname%
	move *.x3f  %_directory%\%_fname%
	move *.xbm  %_directory%\%_fname%
	move *.xcf  %_directory%\%_fname%
	move *.xpm  %_directory%\%_fname%
	move *.xwd  %_directory%\%_fname%
	move *.y  %_directory%\%_fname%
	move *.ysp  %_directory%\%_fname%
	move *.yuv  %_directory%\%_fname%
	move *.zif  %_directory%\%_fname%
		goto end
::____________________________________________done_________________
:text
	 cd /D %_directory%
	 mkdir %_fname%
	 move*.1st %_directory%\%_fname%
	 move *.abw %_directory%\%_fname%
	 move *.act %_directory%\%_fname%
	 move *.aim %_directory%\%_fname%
	 move *.ans %_directory%\%_fname%
	 move *.asc %_directory%\%_fname%
	 move *.asc %_directory%\%_fname%
	 move *.ascii %_directory%\%_fname%
	 move *.ase %_directory%\%_fname%
	 move *.aty %_directory%\%_fname%
	 move *.awp %_directory%\%_fname%
	 move *.awt %_directory%\%_fname%
	 move *.aww %_directory%\%_fname%
	 move *.bad %_directory%\%_fname%
	 move *.bbs %_directory%\%_fname%
	 echo  20% done
	 move *.bdp %_directory%\%_fname%
	 move *.bdr %_directory%\%_fname%
	 move *.bean %_directory%\%_fname%
	 move *.bib %_directory%\%_fname%
	 move *.bib %_directory%\%_fname%
	 move *.bna %_directory%\%_fname%
	 move *.boc %_directory%\%_fname%
	 move *.brx %_directory%\%_fname%
	 move *.btd %_directory%\%_fname%
	 move *.bzabw %_directory%\%_fname%
	 move *.charset %_directory%\%_fname%
	 move *.chord %_directory%\%_fname%
	 move *.cod %_directory%\%_fname%
	 move *.crwl %_directory%\%_fname%
	 move *.cws %_directory%\%_fname%
	 move *.cyi %_directory%\%_fname%
	 move *.dgs %_directory%\%_fname%
	 move *.diz %_directory%\%_fname%
	 move *.dne %_directory%\%_fname%
	 move *.doc %_directory%\%_fname%
	 move *.doc %_directory%\%_fname%
	 move *.docm %_directory%\%_fname%
	 move *.docx %_directory%\%_fname%
	 move *.docxml %_directory%\%_fname%
	 move *.docz %_directory%\%_fname%
	 move *.dotm %_directory%\%_fname%
	 move *.dotx %_directory%\%_fname%
	 move *.dox %_directory%\%_fname%
	 move *.dsc %_directory%\%_fname%
	 move *.dsv %_directory%\%_fname%
	 move *.dvi %_directory%\%_fname%
	 move *.dx %_directory%\%_fname%
	 move *.eml %_directory%\%_fname%
	 move *.emlx %_directory%\%_fname%
	 move *.emulecollection %_directory%\%_fname%
	 move *.epp %_directory%\%_fname%
	 move *.err %_directory%\%_fname%
	 move *.err %_directory%\%_fname%
	 move *.etf %_directory%\%_fname%
	 move *.etx %_directory%\%_fname%
	 move *.euc %_directory%\%_fname%
	 move *.faq %_directory%\%_fname%
	 move *.fb2 %_directory%\%_fname%
	 move *.fbl %_directory%\%_fname%
	 move *.fcf %_directory%\%_fname%
	 move *.fdf %_directory%\%_fname%
	 move *.fdr %_directory%\%_fname%
	 move *.fds %_directory%\%_fname%
	 move *.fdt %_directory%\%_fname%
	 move *.fdx %_directory%\%_fname%
	 move *.fdxt %_directory%\%_fname%
	 move *.fft %_directory%\%_fname%
	 move *.flr %_directory%\%_fname%
	 move *.fodt %_directory%\%_fname%
	 move *.fpt %_directory%\%_fname%
	 move *.frt %_directory%\%_fname%
	 move *.fwdn %_directory%\%_fname%
	 move *.gdoc %_directory%\%_fname%
	 move *.gpn %_directory%\%_fname%
	 move *.gsd %_directory%\%_fname%
	 move *.gthr %_directory%\%_fname%
	 move *.gv %_directory%\%_fname%
	 move *.hht %_directory%\%_fname%
	 move *.hs %_directory%\%_fname%
	 move *.hwp %_directory%\%_fname%
	 move *.hwp %_directory%\%_fname%
	 move *.hz %_directory%\%_fname%
	 move *.idx %_directory%\%_fname%
	 move *.iil %_directory%\%_fname%
	 move *.ipf %_directory%\%_fname%
	 echo  40% done
	 move *.jis %_directory%\%_fname%
	 move *.jp1 %_directory%\%_fname%
	 move *.jrtf %_directory%\%_fname%
	 move *.kes %_directory%\%_fname%
	 move *.klg %_directory%\%_fname%
	 move *.klg %_directory%\%_fname%
	 move *.knt %_directory%\%_fname%
	 move *.kon %_directory%\%_fname%
	 move *.kwd %_directory%\%_fname%
	 move *.latex %_directory%\%_fname%
	 move *.lbt %_directory%\%_fname%
	 move *.lis %_directory%\%_fname%
	 move *.lit %_directory%\%_fname%
	 move *.lnt %_directory%\%_fname%
	 move *.log %_directory%\%_fname%
	 move *.lp2 %_directory%\%_fname%
	 move *.lst %_directory%\%_fname%
	 move *.lst %_directory%\%_fname%
	 move *.ltr %_directory%\%_fname%
	 move *.ltx %_directory%\%_fname%
	 move *.lue %_directory%\%_fname%
	 move *.luf %_directory%\%_fname%
	 move *.lwp %_directory%\%_fname%
	 move *.lxfml %_directory%\%_fname%
	 move *.lyt %_directory%\%_fname%
	 move *.lyx %_directory%\%_fname%
	 move *.man %_directory%\%_fname%
	 move *.mbox %_directory%\%_fname%
	 move *.me %_directory%\%_fname%
	 move *.mell %_directory%\%_fname%
	 move *.mellel %_directory%\%_fname%
	 move *.mnt %_directory%\%_fname%
	 move *.msg %_directory%\%_fname%
	 move *.mw %_directory%\%_fname%
	 move *.mwd %_directory%\%_fname%
	 move *.mwp %_directory%\%_fname%
	 move *.ndoc %_directory%\%_fname%
	 move *.nfo %_directory%\%_fname%
	 move *.njx %_directory%\%_fname%
	 move *.notes %_directory%\%_fname%
	 move *.now %_directory%\%_fname%
	 move *.nwctxt %_directory%\%_fname%
	 move *.ocr %_directory%\%_fname%
	 move *.odif %_directory%\%_fname%
	 move *.odm %_directory%\%_fname%
	 move *.odo %_directory%\%_fname%
	 move *.odt %_directory%\%_fname%
	 move *.ofl %_directory%\%_fname%
	 move *.openbsd %_directory%\%_fname%
	 move *.ort %_directory%\%_fname%
	 move *.ott %_directory%\%_fname%
	 move *.p7s %_directory%\%_fname%
	 move *.pages %_directory%\%_fname%
	 move *.pfx %_directory%\%_fname%
	 move *.pjt %_directory%\%_fname%
	 move *.pmo %_directory%\%_fname%
	 move *.prt %_directory%\%_fname%
	 move *.prt %_directory%\%_fname%
	 move *.psw %_directory%\%_fname%
	 move *.pvj %_directory%\%_fname%
	 move *.pvm %_directory%\%_fname%
	 move *.pwdp %_directory%\%_fname%
	 move *.pwdpl %_directory%\%_fname%
	 move *.pwi %_directory%\%_fname%
	 move *.qdl %_directory%\%_fname%
	 move *.rad %_directory%\%_fname%
	 move *.readme %_directory%\%_fname%
	 move *.rft %_directory%\%_fname%
	 move *.ris %_directory%\%_fname%
	 move *.rpt %_directory%\%_fname%
	 echo  60% done
	 move *.rst %_directory%\%_fname%
	 move *.rtd %_directory%\%_fname%
	 move *.rtf %_directory%\%_fname%
	 move *.rtfd %_directory%\%_fname%
	 move *.rtx %_directory%\%_fname%
	 move *.run %_directory%\%_fname%
	 move *.rzk %_directory%\%_fname%
	 move *.rzn %_directory%\%_fname%
	 move *.saf %_directory%\%_fname%
	 move *.safetext %_directory%\%_fname%
	 move *.sam %_directory%\%_fname%
	 move *.save %_directory%\%_fname%
	 move *.scc %_directory%\%_fname%
	 move *.scm %_directory%\%_fname%
	 move *.scriv %_directory%\%_fname%
	 move *.scrivx %_directory%\%_fname%
	 move *.sct %_directory%\%_fname%
	 move *.scw %_directory%\%_fname%
	 move *.sdm %_directory%\%_fname%
	 move *.sdoc %_directory%\%_fname%
	 move *.sdw %_directory%\%_fname%
	 move *.sgm %_directory%\%_fname%
	 move *.sig %_directory%\%_fname%
	 move *.sla %_directory%\%_fname%
	 move *.sla.gz %_directory%\%_fname%
	 move *.smf %_directory%\%_fname%
	 move *.sms %_directory%\%_fname%
	 move *.ssa %_directory%\%_fname%
	 move *.story %_directory%\%_fname%
	 move *.strings %_directory%\%_fname%
	 move *.stw %_directory%\%_fname%
	 move *.sty %_directory%\%_fname%
	 move *.sub %_directory%\%_fname%
	 move *.sxg %_directory%\%_fname%
	 move *.sxw %_directory%\%_fname%
	 move *.tab %_directory%\%_fname%
	 move *.tab %_directory%\%_fname%
	 move *.tdf %_directory%\%_fname%
	 move *.tdf %_directory%\%_fname%
	 move *.template %_directory%\%_fname%
	 move *.tex %_directory%\%_fname%
	 move *.text %_directory%\%_fname%
	 move *.textclipping %_directory%\%_fname%
	 move *.thp %_directory%\%_fname%
	 move *.tlb %_directory%\%_fname%
	 move *.tm %_directory%\%_fname%
	 move *.tmd %_directory%\%_fname%
	 echo  80% done
	 move *.tpc %_directory%\%_fname%
	 move *.tvj %_directory%\%_fname%
	 move *.txt %_directory%\%_fname%
	 move *.u3i %_directory%\%_fname%
	 move *.unauth %_directory%\%_fname%
	 move *.unx %_directory%\%_fname%
	 move *.uof %_directory%\%_fname%
	 move *.uot %_directory%\%_fname%
	 move *.upd %_directory%\%_fname%
	 move *.utf8 %_directory%\%_fname%
	 move *.utxt %_directory%\%_fname%
	 move *.vct %_directory%\%_fname%
	 move *.vnt %_directory%\%_fname%
	 move *.vw %_directory%\%_fname%
	 move *.wbk %_directory%\%_fname%
	 move *.webdoc %_directory%\%_fname%
	 move *.wn %_directory%\%_fname%
	 move *.wp %_directory%\%_fname%
	 move *.wp4 %_directory%\%_fname%
	 move *.wp5 %_directory%\%_fname%
	 move *.wp6 %_directory%\%_fname%
	 move *.wp7 %_directory%\%_fname%
	 move *.wpa %_directory%\%_fname%
	 move *.wpd %_directory%\%_fname%
	 move *.wpd %_directory%\%_fname%
	 move *.wpd %_directory%\%_fname%
	 move *.wpl %_directory%\%_fname%
	 move *.wps %_directory%\%_fname%
	 move *.wps %_directory%\%_fname%
	 move *.wpt %_directory%\%_fname%
	 move *.wpt %_directory%\%_fname%
	 move *.wpw %_directory%\%_fname%
	 move *.wri %_directory%\%_fname%
	 move *.wsd %_directory%\%_fname%
	 move *.wtx %_directory%\%_fname%
	 move *.xbdoc %_directory%\%_fname%
	 move *.xbplate %_directory%\%_fname%
	 move *.xdl %_directory%\%_fname%
	 move *.xdl %_directory%\%_fname%
	 move *.xwp %_directory%\%_fname%
	 move *.xwp %_directory%\%_fname%
	 move *.xwp %_directory%\%_fname%
	 move *.xy %_directory%\%_fname%
	 move *.xy3 %_directory%\%_fname%
	 move *.xyp %_directory%\%_fname%
	 move *.xyw %_directory%\%_fname%
	 move *.yml %_directory%\%_fname%
	 move *.zabw %_directory%\%_fname%
	 move *.zw %_directory%\%_fname%
	 goto end
::____________________________________________done_________________
:zip
	cd /D %_directory%
	mkdir %_fname%
	move *.zip %_directory%\%_fname%
:custom
		set /p _custom=enter file extention (.exe/.ico): 
		if not '%_custom%'=='%_custom%' set _custom=%_custom%
		cd /D %_directory%
		mkdir %_fname%
		move *%_custom% %_directory%\%_fname%
:end
	 ||cls
	 echo done!
	 echo Lansoftprogramming.com
	 echo (C) 2012 Lansoftprogramming
	 pause
::____________________________________________done_________________
